name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MoMTSim
        uses: actions/checkout@v2
        with:
          path: momtsim
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build MoMTSim
        run: mvn -B package --file momtsim/pom.xml
